application: proppingjay
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /
  script: main.app

- url: /rot13
  script: rot13.app

- url: /ascii
  script: ascii.app

- url: /blog
  script: blog.app

- url: /wiki/
  script: wiki.app

libraries:
- name: jinja2
  version: latest

- name: PIL
  version: "1.1.7"

- name: markupsafe
  version: latest
