
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = ']s\xe3Jv\xc1N\xcd/@\xdbW\xdf\x95.\x9a'
    
_lr_action_items = {'RPAREN':([1,4,5,7,8,9,],[-1,-5,-2,9,-3,-4,]),'LPAREN':([0,1,2,3,4,5,6,7,8,9,],[3,-1,3,3,-5,-2,3,3,-3,-4,]),'ZEROMORE':([1,2,4,5,7,8,9,],[-1,4,-5,4,4,4,-4,]),'LETTER':([0,1,2,3,4,5,6,7,8,9,],[1,-1,1,1,-5,-2,1,1,-3,-4,]),'OR':([1,2,4,5,7,8,9,],[-1,6,-5,-2,6,-3,-4,]),'$end':([1,2,4,5,8,9,],[-1,0,-5,-2,-3,-4,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'re':([0,2,3,5,6,7,8,],[2,5,7,5,8,5,5,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> re","S'",1,None,None,None),
  ('re -> LETTER','re',1,'p_re_letter','RE_final.py',94),
  ('re -> re re','re',2,'p_re_sequence','RE_final.py',98),
  ('re -> re OR re','re',3,'p_re_or','RE_final.py',102),
  ('re -> LPAREN re RPAREN','re',3,'p_re_group','RE_final.py',106),
  ('re -> re ZEROMORE','re',2,'p_re_zeromore','RE_final.py',110),
]
